include::../locale/attributes.adoc[]
= Jim's showroom - demo datasets
:doctype: book
:docinfo:
:icons: font
:toc: left
ifdef::backend-pdf[:toc: macro]
:toc-title: Content
:toclevels: 4
// :sectlinks:
:sectanchors:
:table-stripes: even
:xrefstyle: short


Welcome to the showroom with demo datasets, demonstrating the usage of https://data.norge.no/specification/dcat-ap-no[DCAT-AP-NO, window="_blank", role="ext-link"] (the Norwegian application profile of DCAT for describing datasets, data services and data catalogs)! 

== Purpose [[purpose]] 

This showroom is meant to 

* demonstrate how to use DCAT-AP-NO to describe a dataset and publish the description in a data catalog such that the dataset is findable via the data catalog;
* demonstrate some cross-references between datasets and other resources demonstrated in some of the other showrooms;
* provide reusable, machine-readable datasets and dataset descriptions, for testing and demonstration purposes.

*_Disclaimer_*: _The machine-readable demo datasets are meant for demo purposes only. They do not represent any real world phenomena at all. On the other hand, they are supposed to syntactically conform to DCAT-AP-NO._ 

== Demo resources [[demo-resources]]

In this showroom we have a https://w3id.org/demo-resources/demo-datasets#demoDataset1[demo dataset, called "Demo controlled vocabulary 1"]:

* The demo dataset shown here, is exactly the same as the demo classification called "Demo controlled vocabulary 1" that is demonstrated in https://jimjyang.github.io/showroom/xkos-ap-no/[the showroom with demo classifications]. 
** This is because a classification with its categories _is_ a dataset.   
** The difference is: The showroom here illustrates how to describe a dataset in accordance with DCAT-AP-NO, while the other showroom illustrates how to make available the dataset itself. 
* The demo dataset (= our demo classification) is here described as an open dataset, i.e., with an open licence and made freely available.
* _... #more to come# ..._

 
== Cross-references with other demo resources [[cross-references]]

_... #more to come# ..._

== _to the overview of the showrooms_ [[to-overview]]

https://jimjyang.github.io/showroom/#overview[Click here for the overview of all the showrooms]