include::../locale/attributes.adoc[]
= Jim's showroom - demo concepts
:doctype: book
:docinfo:
:icons: font
:toc: left
ifdef::backend-pdf[:toc: macro]
:toc-title: Content
:toclevels: 4
// :sectlinks:
:sectanchors:
:table-stripes: even


// _Updated: 2023-03-20_

In this part of the showroom we will demonstrate the usage of https://data.norge.no/specification/skos-ap-no-begrep[SKOS-AP-NO-Begrep] (the Norwegian application profile of SKOS for describing and publishing concepts and concept collections). 

We have here

* a link:files/demo-concepts.ttl[RDF Turtle file] with demo concepts illustrating the usage of SKOS-AP-NO-Begrep
** The demo concepts will be automatically harvested to and thus published via the demo catalog, after the catalog is modified to harvesting concept descriptions in accordance with v.2 of SKOS-AP-NO-Begrep.
** These demo concepts are currently meant to 
*** demonstrate how to describe concepts in accordance with SKOS-AP-NO-Begrep.
*** demonstrate how to describe relations between concepts, in accordance with SKOS-AP-NO-Begrep.   
*** be referenced to as machine-readable RDF resources, for testing and demonstration purposes. 
* _... more to come_
