include::../locale/attributes.adoc[]
= Jim's showroom - demo information models
:doctype: book
:docinfo:
:icons: font
:toc: left
ifdef::backend-pdf[:toc: macro]
:toc-title: Content
:toclevels: 4
// :sectlinks:
:sectanchors:
:table-stripes: even


// _Updated: 2023-03-20_

Welcome to the showroom with demo information models, demonstrating the usage of https://data.norge.no/specification/modelldcat-ap-no[ModellDCAT-AP-NO, window="_blank", role="ext-link"] (the Norwegian application profile of DCAT for describing information models and catalogs of information models)!

== Purpose [[purpose]]

This showroom is meant to

* demonstrate how to describe an information model in accordance with ModellDCAT-AP-NO, at the model level (i.e., without describing the model elements)
* demonstrate how to describe relations between information models, in accordance with ModellDCAT-AP-NO
* demonstrate cross-references between information models and some other resources demonstrated in some of the other showrooms
* provided reusable, machine-readable RDF-based model descriptions, for testing and demonstration purposes
 
*_Disclaimer_*: _The machine-readable demo information models are meant for demo purposes only. They do not represent any real world fenomena at all. On the other hand, they are supposed to syntactically conform to ModellDCAT-AP-NO v.1.x._

== Demo resources [[demo-resources]]

In this showroom we have a https://w3id.org/demo-resources/demo-models[a catalog with several demo information models]:

* The demo models are automatically harvested to and thus findable via https://demo.fellesdatakatalog.digdir.no/informationmodels?q=demomodel[the demo catalog]. 


_#... more may come ...#_  

== Cross-references with other demo resources [[cross-references]]

An information model may refer to:

* A concept _#... more to come ...#_   
* A classification (controlled vocabulary) _#... more to come ...#_ 
* _#... more to come ...#_ 

An information model may be referred to from:

* A dataset _#... more to come ...#_ 
* _#... more to come ...#_  

== _to the overview of the showrooms_ [[to-overview]]

https://jimjyang.github.io/showroom/#showrooms[Click here for the overview of all the showrooms]