include::../locale/attributes.adoc[]
= Jim's showroom - demo information models
:doctype: book
:docinfo:
:icons: font
:toc: left
ifdef::backend-pdf[:toc: macro]
:toc-title: Content
:toclevels: 4
// :sectlinks:
:sectanchors:
:table-stripes: even


// _Updated: 2023-03-20_

Welcome to the showroom for https://data.norge.no/specification/modelldcat-ap-no[ModellDCAT-AP-NO] (the Norwegian application profile of DCAT for describing information models, _in Norwegian only_)!

We have here 

* a link:files/demo-models.ttl[RDF Turtle file] with demo information models illustrating the usage of ModellDCAT-AP-NO
** The demo models are automatically harvested to and thus published via the ModellDCAT-AP-NO. 
** These demo models are currently meant to 
*** demonstrate how to describe an information model in accordance with ModellDCAT-AP-NO, at the model level (i.e., without describing the model elements), and how to link to online resources of the model where more descriptions of the model may be found.
*** demonstrate how to describe relations between information models, in accordance with ModellDCAT-AP-NO.   
*** be referenced to as machine-readable RDF resources, for testing and demonstration purposes. 
* _... more may come_
