== Making the resources available through national data portal [[about-demo-portal]]

The Norwegian national specifications demonstrated in the various showrooms here, are also meant to be used to make the descriptions (metadata) of the resources available machine-readably, e.g. through the https://data.norge.no/[the National Data Catalog of Norway ↗, window="_blank", role="ext-link"] maintained by the Norwegian Digitalisation Agency. 

In order to make the resources available/findable through the National Data Catalog, you may 

. use the editors to register metadata (descriptions) about your resources (datasets, concepts etc.) which will be automatically harvested into the National Data Portal, or 
. use the harvesting services to specify the URLs where your machine-readable descriptions are made available for harvesting into the National Data Catalog.   

There is also a https://demo.fellesdatakatalog.digdir.no/[demo portal ↗, window="_blank", role="ext-link"] provided by the Norwegian Digitalisation Agency, which has the same functionalities as the National Data Catalog, but the content is only for testing and demonstration purposes. 

Using the harvesting services, most (if mot all) of the demo resources that are demonstrated in the various showrooms here are, or will be, automatically harvested to and thus findable via the demo portal. 

Examples for how to find some of the demo resources in the demo portal:

* demo classifications / datasets: by for instance https://demo.fellesdatakatalog.digdir.no/datasets?q=demodataset[searching "demodataset" in the "Datasets" part of the demo portal ↗, window="_blank", role="ext-link"].
* demo concepts (#not yet published there#): by for instance https://demo.fellesdatakatalog.digdir.no/concepts?q=demoCpt[searching "demoCpt" in the "Concepts" part of the demo portal ↗, window="_blank", role="ext-link"]. 
* demo information models: by for instance https://demo.fellesdatakatalog.digdir.no/informationmodels?q=demomodel[searching "demomodel" in the "Information models" part of the demo portal ↗, window="_blank", role="ext-link"].
* _#... more may come ...#_

